### ISSUE TITLE
Dataset Viewer issue for krr-oxford/OntoLAMA

### ISSUE THREAD

**Issue by Lawhy** [huggingface/datasets-server#1118]
### Link

https://huggingface.co/datasets/krr-oxford/OntoLAMA

### Description

The dataset viewer is not working for dataset krr-oxford/OntoLAMA.

Error details:

```
Error code:   ConfigNamesError
Exception:    OSError
Message:      [Errno 28] No space left on device: '/datasets-server-cache/all/datasets/2023-05-02-16-09-38--config-names-krr-oxford-OntoLAMA-1fc33233/downloads'
Traceback:    The previous step failed, the error is copied to this step:  kind='dataset-info' dataset='krr-oxford/OntoLAMA' config=None split=None---The previous step failed, the error is copied to this step:  kind='/config-names' dataset='krr-oxford/OntoLAMA' config=None split=None---Traceback (most recent call last):
                File "/src/services/worker/src/worker/job_runners/config_names.py", line 99, in compute_config_names_response
                  for config in sorted(get_dataset_config_names(path=dataset, use_auth_token=use_auth_token))
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/inspect.py", line 323, in get_dataset_config_names
                  dataset_module = dataset_module_factory(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1215, in dataset_module_factory
                  raise e1 from None
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1184, in dataset_module_factory
                  return HubDatasetModuleFactoryWithScript(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 901, in get_module
                  local_path = self.download_loading_script()
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 869, in download_loading_script
                  return cached_path(file_path, download_config=download_config)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 183, in cached_path
                  output_path = get_from_cache(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 470, in get_from_cache
                  os.makedirs(cache_dir, exist_ok=True)
                File "/usr/local/lib/python3.9/os.py", line 225, in makedirs
                  mkdir(name, mode)
              OSError: [Errno 28] No space left on device: '/datasets-server-cache/all/datasets/2023-05-02-16-09-38--config-names-krr-oxford-OntoLAMA-1fc33233/downloads'
```

**Comment by albertvillanova** [comment]
Thanks for reporting, @Lawhy.

We had an issue with disk space on our datasets server, but this has already been fixed.

Now your dataset viewer shows an `IndexError`:
```
IndexError: list index out of range
```

Note this is an error we get sometimes when data files are hosted on Zenodo, caused by a 429 HTTP error (Too many requests). We are working to give a more informative error message.

In the meantime, to make the viewer work, and only if the license allows it, you could host the data files on the Hugging Face Hub itself.

**Comment by albertvillanova** [comment]
See current stack trace:
```
Error code:   StreamingRowsError
Exception:    IndexError
Message:      list index out of range
Traceback:    Traceback (most recent call last):
                File "/src/services/worker/src/worker/utils.py", line 327, in get_rows_or_raise
                  return get_rows(
                File "/src/services/worker/src/worker/utils.py", line 271, in decorator
                  return func(*args, **kwargs)
                File "/src/services/worker/src/worker/utils.py", line 307, in get_rows
                  rows_plus_one = list(itertools.islice(ds, rows_max_number + 1))
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 937, in __iter__
                  for key, example in ex_iterable:
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 113, in __iter__
                  yield from self.generate_examples_fn(**self.kwargs)
                File "/tmp/modules-cache/datasets_modules/datasets/krr-oxford--OntoLAMA/efb5cb066b4abc4e99e58f9cfce231e1a62c8c267298b50fd1394805c2400d00/OntoLAMA.py", line 187, in _generate_examples
                  with open(filepath, encoding="utf-8") as f:
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/streaming.py", line 71, in wrapper
                  return function(*args, use_auth_token=use_auth_token, **kwargs)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/download/streaming_download_manager.py", line 498, in xopen
                  file_obj = fsspec.open(file, mode=mode, *args, **kwargs).open()
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/core.py", line 419, in open
                  return open_files(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/core.py", line 272, in open_files
                  fs, fs_token, paths = get_fs_token_paths(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/core.py", line 586, in get_fs_token_paths
                  fs = filesystem(protocol, **inkwargs)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/registry.py", line 253, in filesystem
                  return cls(**storage_options)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/spec.py", line 76, in __call__
                  obj = super().__call__(*args, **kwargs)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/implementations/zip.py", line 54, in __init__
                  fo = fsspec.open(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/core.py", line 419, in open
                  return open_files(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/core.py", line 194, in __getitem__
                  out = super().__getitem__(item)
              IndexError: list index out of range
```

**Comment by albertvillanova** [comment]
The corresponding issue in the Community tab of the dataset: https://huggingface.co/datasets/krr-oxford/OntoLAMA/discussions/1
