### ISSUE TITLE
Dataset Viewer issue for hendrycks_test

### ISSUE THREAD

**Issue by surya-narayanan** [huggingface/datasets-server#1152]
### Link

https://huggingface.co/datasets/hendrycks_test

### Description

The dataset viewer is not working for dataset hendrycks_test.

Error details:

```
Error code:   ExternalFilesSizeRequestConnectionError
Exception:    ConnectionError
Message:      HTTPSConnectionPool(host='people.eecs.berkeley.edu', port=443): Max retries exceeded with url: /~hendrycks/data.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdb011d5cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback:    The previous step failed, the error is copied to this step:  kind='config-parquet' dataset='hendrycks_test' config='philosophy' split=None---The previous step failed, the error is copied to this step:  kind='config-parquet-and-info' dataset='hendrycks_test' config='philosophy' split=None---Traceback (most recent call last):
                File "/src/services/worker/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
                  conn = connection.create_connection(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
                  raise err
                File "/src/services/worker/.venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
                  sock.connect(sa)
              ConnectionRefusedError: [Errno 111] Connection refused
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/src/services/worker/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
                  httplib_response = self._make_request(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
                  self._validate_conn(conn)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
                  conn.connect()
                File "/src/services/worker/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
                  self.sock = conn = self._new_conn()
                File "/src/services/worker/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
                  raise NewConnectionError(
              urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fdb011d5cd0>: Failed to establish a new connection: [Errno 111] Connection refused
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/src/services/worker/.venv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
                  resp = conn.urlopen(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
                  retries = retries.increment(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
                  raise MaxRetryError(_pool, url, error or ResponseError(cause))
              urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='people.eecs.berkeley.edu', port=443): Max retries exceeded with url: /~hendrycks/data.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdb011d5cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 624, in raise_if_too_big_from_external_data_files
                  for i, size in enumerate(pool.imap_unordered(get_size, ext_data_files)):
                File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 870, in next
                  raise value
                File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 125, in worker
                  result = (True, func(*args, **kwds))
                File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 519, in _request_size
                  response = http_head(url, headers=headers, max_retries=3)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 413, in http_head
                  response = _request_with_retry(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 324, in _request_with_retry
                  raise err
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 320, in _request_with_retry
                  response = requests.request(method=method.upper(), url=url, timeout=timeout, **params)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
                  return session.request(method=method, url=url, **kwargs)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
                  resp = self.send(prep, **send_kwargs)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
                  r = adapter.send(request, **kwargs)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
                  raise ConnectionError(e, request=request)
              requests.exceptions.ConnectionError: HTTPSConnectionPool(host='people.eecs.berkeley.edu', port=443): Max retries exceeded with url: /~hendrycks/data.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdb011d5cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by albertvillanova** [comment]
Thanks for reporting, @surya-narayanan.

Yesterday we had an outage affecting multiple Hugging Face services. It is fixed now and the viewers are progressively updating.

The viewer for "hendrycks_test" is working now. See: 

![Screenshot from 2023-05-10 09-30-11](https://github.com/huggingface/datasets-server/assets/8515462/85e8b86b-1933-49cd-9484-5fede43c16e9)
