### ISSUE TITLE
The workers fail with `mongoengine.errors.FieldDoesNotExist: The fields "{'force'}" do not exist on the document "Job"`

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1182]
```
INFO: 2023-05-13 10:50:18,007 - root - Worker loop started
INFO: 2023-05-13 10:50:18,023 - root - Starting heartbeat.
ERROR: 2023-05-13 10:50:18,115 - asyncio - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<every() done, defined at /src/services/worker/src/worker/executor.py:26> exception=FieldDoesNotExist('The fields "{\'force\'}" do not exist on the document "Job"')>
Traceback (most recent call last):
  File "/src/services/worker/src/worker/executor.py", line 30, in every
    out = func(*args, **kwargs)
  File "/src/services/worker/src/worker/executor.py", line 117, in kill_zombies
    zombies = queue.get_zombies(max_seconds_without_heartbeat=self.max_seconds_without_heartbeat_for_zombies)
  File "/src/libs/libcommon/src/libcommon/queue.py", line 622, in get_zombies
    zombies = [
  File "/src/libs/libcommon/src/libcommon/queue.py", line 622, in <listcomp>
    zombies = [
  File "/src/services/worker/.venv/lib/python3.9/site-packages/mongoengine/queryset/queryset.py", line 110, in _iter_results
    self._populate_cache()
  File "/src/services/worker/.venv/lib/python3.9/site-packages/mongoengine/queryset/queryset.py", line 129, in _populate_cache
    self._result_cache.append(next(self))
  File "/src/services/worker/.venv/lib/python3.9/site-packages/mongoengine/queryset/base.py", line 1599, in __next__
    doc = self._document._from_son(
  File "/src/services/worker/.venv/lib/python3.9/site-packages/mongoengine/base/document.py", line 836, in _from_son
    obj = cls(__auto_convert=False, _created=created, **data)
  File "/src/services/worker/.venv/lib/python3.9/site-packages/mongoengine/base/document.py", line 99, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'force'}" do not exist on the document "Job"
Traceback (most recent call last):
  File "/src/services/worker/src/worker/main.py", line 61, in <module>
    worker_executor.start()
  File "/src/services/worker/src/worker/executor.py", line 89, in start
    loop.run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 645, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```

<img width="622" alt="Capture d’écran 2023-05-13 à 12 52 06" src="https://github.com/huggingface/datasets-server/assets/1676121/3e4d7e1a-dd02-476d-b671-57ce03d28d7b">

**Comment by severo** [comment]
Maybe due to 298 jobs that still contain the "force" field in the database? They were created yesterday between 2023-05-12T16:45:25.465+00:00 and 2023-05-12T16:46:21.671+00:00, ie. during the deployment of the last version. Possibly we have to resync to get rid of them. Trying that

**Comment by severo** [comment]
Note also that the jobs seem to be increasing only:

<img width="363" alt="Capture d’écran 2023-05-13 à 12 56 34" src="https://github.com/huggingface/datasets-server/assets/1676121/2ab2baed-d59f-4c1b-b349-a9f7678166aa">

**Comment by severo** [comment]
I manually deleted the three last entries in the maintenance collection so that the migrations will be run again on the next sync


<img width="404" alt="Capture d’écran 2023-05-13 à 13 01 50" src="https://github.com/huggingface/datasets-server/assets/1676121/a5091d29-d4c9-4ef2-9116-e0ba3053b4dd">

**Comment by severo** [comment]
Sync'ed again, the migrations have been applied:

```
INFO: 2023-05-13 11:03:52,593 - root - Start migrations
INFO: 2023-05-13 11:03:52,657 - root - 25 migrations have already been applied. They will be skipped.
INFO: 2023-05-13 11:03:52,657 - root - Migrate 20230511100600: add to the migrations collection
INFO: 2023-05-13 11:03:52,663 - root - Migrate 20230511100600: apply
INFO: 2023-05-13 11:03:52,663 - root - Removing 'force' field.
INFO: 2023-05-13 11:03:53,753 - root - Migrate 20230511100600: validate
INFO: 2023-05-13 11:03:53,753 - root - Ensure that a random selection of cached results don't have 'force' field
INFO: 2023-05-13 11:03:53,814 - root - Migrate 20230511100600: done
INFO: 2023-05-13 11:03:53,814 - root - Migrate 20230511100700: add to the migrations collection
INFO: 2023-05-13 11:03:53,819 - root - Migrate 20230511100700: apply
INFO: 2023-05-13 11:03:53,819 - root - Delete indexes that contain the force field.
INFO: 2023-05-13 11:03:53,821 - root - Migrate 20230511100700: validate
INFO: 2023-05-13 11:03:53,821 - root - Check that the indexes do not exist anymore
INFO: 2023-05-13 11:03:53,823 - root - Migrate 20230511100700: done
INFO: 2023-05-13 11:03:53,823 - root - Migrate 20230511110700: add to the migrations collection
INFO: 2023-05-13 11:03:53,828 - root - Migrate 20230511110700: apply
INFO: 2023-05-13 11:03:53,828 - root - Delete jobs with status skipped.
INFO: 2023-05-13 11:03:53,951 - root - Migrate 20230511110700: validate
INFO: 2023-05-13 11:03:53,951 - root - Ensure that a random selection of cached results don't have the status {status}
INFO: 2023-05-13 11:03:53,994 - root - Migrate 20230511110700: done
INFO: 2023-05-13 11:03:53,994 - root - All migrations have been applied
```

The jobs collection does not contain jobs with the 'force' field anymore.

**Comment by severo** [comment]
OK, it was only part of the problem. The main issue seems to be that the loop breaks, and thus the pod crashes, on every exception (even those that we expect)! It seems like an `except` clause has been changed

**Comment by severo** [comment]
The issue seems to be with uncaught exception when getting the git revision of the dataset. Fix is in #1183.

This means that we should change a bit the paradigm: a job should include a git revision in its parameters, instead of trying to fetch it by itself

**Comment by severo** [comment]
It seems to have been fixed

<img width="329" alt="Capture d’écran 2023-05-13 à 13 32 21" src="https://github.com/huggingface/datasets-server/assets/1676121/b8c3361f-66a7-4a3d-8059-251d124c2d0c">

**Comment by severo** [comment]
We currently have 5000 waiting jobs. Hopefully we will flush them quickly

**Comment by severo** [comment]
There is still an issue in the logs:

```
... not the STARTED status (cancelled). Force finishing anyway.
WARNING: 2023-05-13 11:35:17,005 - root - job dataset-opt-in-out-urls-count,makiligon/vocal-theft-spree has a non-empty finished_at field. Force finishing anyway.
```

**Comment by severo** [comment]
Everything flushed
<img width="139" alt="Capture d’écran 2023-05-13 à 14 42 31" src="https://github.com/huggingface/datasets-server/assets/1676121/f9f26e88-2744-4404-9e9f-ca0b7983d778">

**Comment by albertvillanova** [comment]
Thanks for taking care of the issue...

**Comment by severo** [comment]
Fixed
