### ISSUE TITLE
Don't return an error on /first-rows (or later: /rows) if one image is failing

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1192]
See https://huggingface.co/datasets/datadrivenscience/ship-detection

<img width="1034" alt="Capture d’écran 2023-05-17 à 14 33 42" src="https://github.com/huggingface/datasets-server/assets/1676121/9e12612f-bb42-4460-8c7d-91fc75534518">

```
Error code:   StreamingRowsError
Exception:    DecompressionBombError
Message:      Image size (806504000 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
Traceback:    Traceback (most recent call last):
                File "/src/services/worker/src/worker/utils.py", line 327, in get_rows_or_raise
                  return get_rows(
                File "/src/services/worker/src/worker/utils.py", line 271, in decorator
                  return func(*args, **kwargs)
                File "/src/services/worker/src/worker/utils.py", line 307, in get_rows
                  rows_plus_one = list(itertools.islice(ds, rows_max_number + 1))
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 941, in __iter__
                  yield _apply_feature_types_on_example(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 700, in _apply_feature_types_on_example
                  decoded_example = features.decode_example(encoded_example, token_per_repo_id=token_per_repo_id)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/features/features.py", line 1864, in decode_example
                  return {
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/features/features.py", line 1865, in <dictcomp>
                  column_name: decode_nested_example(feature, value, token_per_repo_id=token_per_repo_id)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/features/features.py", line 1308, in decode_nested_example
                  return schema.decode_example(obj, token_per_repo_id=token_per_repo_id)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/features/image.py", line 175, in decode_example
                  image = PIL.Image.open(bytes_)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/PIL/Image.py", line 3268, in open
                  im = _open_core(fp, filename, prefix, formats)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/PIL/Image.py", line 3255, in _open_core
                  _decompression_bomb_check(im.size)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/PIL/Image.py", line 3164, in _decompression_bomb_check
                  raise DecompressionBombError(msg)
              PIL.Image.DecompressionBombError: Image size (806504000 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
```

One image is too big to be processed (or maybe some images), but the other images are smaller. We should return the response to `/first-rows`, but have a way to indicate that some of the cells have an error (as we already have `truncated_cells`)

**Comment by severo** [comment]
Copying references found by @albertvillanova 

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.open

> If the number of pixels is greater than twice MAX_IMAGE_PIXELS, then a DecompressionBombError will be raised instead.

> This threshold can be changed by setting MAX_IMAGE_PIXELS. It can be disabled by setting Image.MAX_IMAGE_PIXELS = None.

> The default value for MAX_IMAGE_PIXELS is 0.25GB, which allows opening images up to 0.5GB (twice the value)

**Comment by severo** [comment]
See #1361
