### ISSUE TITLE
Dataset Viewer issue for phamson02/vietnamese-poetry-corpus

### ISSUE THREAD

**Issue by phamson02** [huggingface/datasets-server#1202]
### Link

https://huggingface.co/datasets/phamson02/vietnamese-poetry-corpus

### Description

The dataset viewer is not working for dataset phamson02/vietnamese-poetry-corpus.

Error details:

```
Error code:   ConfigNamesError
Exception:    OSError
Message:      [Errno 116] Stale file handle
Traceback:    Traceback (most recent call last):
                File "/src/services/worker/src/worker/job_runners/dataset/config_names.py", line 61, in compute_config_names_response
                  for config in sorted(get_dataset_config_names(path=dataset, use_auth_token=use_auth_token))
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/inspect.py", line 323, in get_dataset_config_names
                  dataset_module = dataset_module_factory(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1219, in dataset_module_factory
                  raise e1 from None
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1196, in dataset_module_factory
                  return HubDatasetModuleFactoryWithoutScript(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 829, in get_module
                  dataset_readme_path = cached_path(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 183, in cached_path
                  output_path = get_from_cache(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 611, in get_from_cache
                  http_get(
                File "/usr/local/lib/python3.9/tempfile.py", line 496, in __exit__
                  result = self.file.__exit__(exc, value, tb)
              OSError: [Errno 116] Stale file handle
```

**Comment by albertvillanova** [comment]
Thanks for reporting, @phamson02.

I have forced the refresh of the viewer and it is fixed now:

![Screenshot from 2023-05-22 08-52-31](https://github.com/huggingface/datasets-server/assets/8515462/e87d2d8b-352b-4e68-adb3-19bc07692d48)
