### ISSUE TITLE
Dataset Viewer issue for ceval/ceval-exam

### ISSUE THREAD

**Issue by jxhe** [huggingface/datasets-server#1216]
### Link

https://huggingface.co/datasets/ceval/ceval-exam

### Description

The dataset viewer is not working for dataset ceval/ceval-exam.

Error details:

```
Error code:   ConfigNamesError
Exception:    FileNotFoundError
Message:      Couldn't find a dataset script at /src/services/worker/ceval/ceval-exam/ceval-exam.py or any data file in the same directory. Couldn't find 'ceval/ceval-exam' on the Hugging Face Hub either: FileNotFoundError: [Errno 2] No such file or directory: '/datasets-server-cache/all/datasets/2023-05-18-14-02-51--config-names-ceval-ceval-exam-978bb85a/downloads/7a60e8ce0ce0606a529d46c365947855cbb11c87fdf815889826fb1c727b54f1.7dae390f456cff1d62f338fbf3c7dcdbc9c8ab289a0c591434fadb67af7702dd.py'
Traceback:    Traceback (most recent call last):
                File "/src/services/worker/src/worker/job_runners/dataset/config_names.py", line 61, in compute_config_names_response
                  for config in sorted(get_dataset_config_names(path=dataset, use_auth_token=use_auth_token))
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/inspect.py", line 323, in get_dataset_config_names
                  dataset_module = dataset_module_factory(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1215, in dataset_module_factory
                  raise FileNotFoundError(
              FileNotFoundError: Couldn't find a dataset script at /src/services/worker/ceval/ceval-exam/ceval-exam.py or any data file in the same directory. Couldn't find 'ceval/ceval-exam' on the Hugging Face Hub either: FileNotFoundError: [Errno 2] No such file or directory: '/datasets-server-cache/all/datasets/2023-05-18-14-02-51--config-names-ceval-ceval-exam-978bb85a/downloads/7a60e8ce0ce0606a529d46c365947855cbb11c87fdf815889826fb1c727b54f1.7dae390f456cff1d62f338fbf3c7dcdbc9c8ab289a0c591434fadb67af7702dd.py'
```

**Comment by albertvillanova** [comment]
Thanks for reporting, @jxhe.

I have forced the refresh of the viewer and now it shows another error message:
```
NotImplementedError: Extraction protocol for TAR archives like 'https://huggingface.co/datasets/ceval/ceval-exam/resolve/main/ceval_data.tar' is not implemented in streaming mode. Please use `dl_manager.iter_archive` instead.
```
I have opened a discussion in the Community tab of the dataset: https://huggingface.co/datasets/ceval/ceval-exam/discussions/1
Let's continue the discussion there.
