### ISSUE TITLE
Dataset Viewer issue for kietzmannlab/ecoset

### ISSUE THREAD

**Issue by v-bosch** [huggingface/datasets-server#1224]
### Link

https://huggingface.co/datasets/kietzmannlab/ecoset

### Description

The dataset viewer is not working for dataset kietzmannlab/ecoset.

Error details:

```
Error code:   ConfigNamesError
Exception:    ImportError
Message:      To be able to use kietzmannlab/ecoset, you need to install the following dependencies: boto3, botocore.
Please install them using 'pip install boto3 botocore' for instance.
Traceback:    The previous step failed, the error is copied to this step:  kind='/config-names' dataset='kietzmannlab/ecoset' config=None split=None---Traceback (most recent call last):
                File "/src/workers/datasets_based/src/datasets_based/workers/config_names.py", line 89, in compute_config_names_response
                  for config in sorted(get_dataset_config_names(path=dataset, use_auth_token=use_auth_token))
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/inspect.py", line 323, in get_dataset_config_names
                  dataset_module = dataset_module_factory(
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/load.py", line 1217, in dataset_module_factory
                  raise e1 from None
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/load.py", line 1188, in dataset_module_factory
                  return HubDatasetModuleFactoryWithScript(
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/load.py", line 907, in get_module
                  local_imports = _download_additional_modules(
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/load.py", line 221, in _download_additional_modules
                  raise ImportError(
              ImportError: To be able to use kietzmannlab/ecoset, you need to install the following dependencies: boto3, botocore.
              Please install them using 'pip install boto3 botocore' for instance.
```

**Comment by severo** [comment]
Should we close since we will not support script based datasets?
