### ISSUE TITLE
Dataset Viewer issue for vishnun/NLP-KnowledgeGraph

### ISSUE THREAD

**Issue by MangoFF** [huggingface/datasets-server#1230]
### Link

https://huggingface.co/datasets/vishnun/NLP-KnowledgeGraph

### Description

The dataset viewer is not working for dataset vishnun/NLP-KnowledgeGraph.

Error details:

```
Error code:   ConfigNamesError
Exception:    OSError
Message:      [Errno 116] Stale file handle
Traceback:    The previous step failed, the error is copied to this step:  kind='/config-names' dataset='vishnun/NLP-KnowledgeGraph' config=None split=None---Traceback (most recent call last):
                File "/src/services/worker/src/worker/job_runners/config_names.py", line 99, in compute_config_names_response
                  for config in sorted(get_dataset_config_names(path=dataset, use_auth_token=use_auth_token))
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/inspect.py", line 323, in get_dataset_config_names
                  dataset_module = dataset_module_factory(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1215, in dataset_module_factory
                  raise e1 from None
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1192, in dataset_module_factory
                  return HubDatasetModuleFactoryWithoutScript(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 825, in get_module
                  dataset_readme_path = cached_path(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 183, in cached_path
                  output_path = get_from_cache(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/utils/file_utils.py", line 611, in get_from_cache
                  http_get(
                File "/usr/local/lib/python3.9/tempfile.py", line 496, in __exit__
                  result = self.file.__exit__(exc, value, tb)
              OSError: [Errno 116] Stale file handle
```

**Comment by albertvillanova** [comment]
Thanks for reporting, @MangoFF.

We are having issues with the datasets-serve.

We'll keep you informed once the issues are fixed.

**Comment by albertvillanova** [comment]
The issues with the datasets-server were fixed and I have forced the refresh of your viewer.

It works as expected now:

![Screenshot from 2023-05-30 09-26-31](https://github.com/huggingface/datasets-server/assets/8515462/78e4a27f-d1ce-446b-8eb9-9daf6b63459d)
