### ISSUE TITLE
Dataset Viewer issue for fabraz/writingPromptAug

### ISSUE THREAD

**Issue by Patrick-Ni** [huggingface/datasets-server#1243]
### Link

https://huggingface.co/datasets/fabraz/writingPromptAug

### Description

The dataset viewer is not working for dataset fabraz/writingPromptAug.

Error details:

```
Error code:   ConfigNamesError
Exception:    ValueError
Message:      Split train already present
Traceback:    The previous step failed, the error is copied to this step:  kind='/config-names' dataset='fabraz/writingPromptAug' config=None split=None---Traceback (most recent call last):
                File "/src/workers/datasets_based/src/datasets_based/workers/config_names.py", line 89, in compute_config_names_response
                  for config in sorted(get_dataset_config_names(path=dataset, use_auth_token=use_auth_token))
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/inspect.py", line 323, in get_dataset_config_names
                  dataset_module = dataset_module_factory(
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/load.py", line 1217, in dataset_module_factory
                  raise e1 from None
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/load.py", line 1196, in dataset_module_factory
                  return HubDatasetModuleFactoryWithoutScript(
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/load.py", line 834, in get_module
                  builder_kwargs["info"] = DatasetInfo._from_yaml_dict(dataset_info_dict)
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/info.py", line 400, in _from_yaml_dict
                  yaml_data["splits"] = SplitDict._from_yaml_list(yaml_data["splits"])
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/splits.py", line 598, in _from_yaml_list
                  return cls.from_split_dict(yaml_data)
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/splits.py", line 570, in from_split_dict
                  split_dict.add(split_info)
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/splits.py", line 547, in add
                  raise ValueError(f"Split {split_info.name} already present")
              ValueError: Split train already present
```

**Comment by albertvillanova** [comment]
Thanks for reporting, @Patrick-Ni.

The cause of this issue is a duplicated split name in the dataset card metadata. 
I have opened an issue in the Community tab of the dataset: https://huggingface.co/datasets/fabraz/writingPromptAug/discussions/1
Let's continue the discussion there!
