### ISSUE TITLE
Avoid commit conflicts

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#1396]
See https://github.com/huggingface/datasets-server/issues/1163#issuecomment-1598504866 and following comments

- [ ] add tests to check if `parent_commit=parent_commit if not commit_infos else commit_infos[-1].oid` is correct
- [ ] add write/read concern for the lock requests to ensure consistency
- [ ] ???

**Comment by severo** [comment]
Comment on https://discuss.huggingface.co/t/strange-problems-with-datasets-server/43871 when we fix the bug

**Comment by severo** [comment]
Testing on https://huggingface.co/datasets/severo/flores_101 (clone of https://huggingface.co/datasets/gsarti/flores_101 which is mentioned in the forum: https://discuss.huggingface.co/t/strange-problems-with-datasets-server/43871)

The dataset has 103 configs (https://datasets-server.huggingface.co/config-names?dataset=severo/flores_101), from `afr` to `zul`, including the special `all`. Every config has two splits: `dev` and `devtest`.

**Comment by severo** [comment]
On https://datasets-server.huggingface.co/splits?dataset=severo/flores_101, we get one failed response, for config `all`. We will ignore it for the analysis.

**Comment by severo** [comment]
The /parquet endpoint (https://datasets-server.huggingface.co/parquet?dataset=severo/flores_101) gives:
- a list of 94 parquet files, corresponding to 94 splits since the files are small (no shards), ie. about 47 configs
- a list of 56 failed configurations

**Comment by severo** [comment]
The failed configurations have the same error, ie https://datasets-server.huggingface.co/parquet?dataset=severo/flores_101&config=afr gives:

```
{"error":"Commit 0/1 could not be created on the Hub (after 6 attempts)."}
```

In the database, we get more details (in the ...`details` field)

```
> db.cachedResponsesBlue.find({kind:"config-parquet-and-info", dataset: "severo/flores_101", config: "afr"})
< { _id: ObjectId("6491fa987db6962fea73bcd2"),
  config: 'afr',
  dataset: 'severo/flores_101',
  kind: 'config-parquet-and-info',
  split: null,
  content: { error: 'Commit 0/1 could not be created on the Hub (after 6 attempts).' },
  dataset_git_revision: 'bc58ae43b22607b3e1e2bf3ae1bc5cb053495abb',
  details: 
   { error: 'Commit 0/1 could not be created on the Hub (after 6 attempts).',
     cause_exception: 'HfHubHTTPError',
     cause_message: '412 Client Error: Precondition Failed for url: https://huggingface.co/api/datasets/severo/flores_101/commit/refs%2Fconvert%2Fparquet (Request ID: Root=1-6491fa98-263a2ada63bac64a0bd5fb2d)\n\nA commit has happened since. Please refresh and try again.',
     cause_traceback: 
      [ 'Traceback (most recent call last):\n',
        '  File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status\n    response.raise_for_status()\n',
        '  File "/src/services/worker/.venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n',
        'requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: https://huggingface.co/api/datasets/severo/flores_101/commit/refs%2Fconvert%2Fparquet\n',
        '\nThe above exception was the direct cause of the following exception:\n\n',
        'Traceback (most recent call last):\n',
        '  File "/src/services/worker/src/worker/utils.py", line 317, in decorator\n    return func(*args, **kwargs)\n',
        '  File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn\n    return fn(*args, **kwargs)\n',
        '  File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 828, in _inner\n    return fn(self, *args, **kwargs)\n',
        '  File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 2728, in create_commit\n    hf_raise_for_status(commit_resp, endpoint_name="commit")\n',
        '  File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 301, in hf_raise_for_status\n    raise HfHubHTTPError(str(e), response=response) from e\n',
        'huggingface_hub.utils._errors.HfHubHTTPError: 412 Client Error: Precondition Failed for url: https://huggingface.co/api/datasets/severo/flores_101/commit/refs%2Fconvert%2Fparquet (Request ID: Root=1-6491fa98-263a2ada63bac64a0bd5fb2d)\n\nA commit has happened since. Please refresh and try again.\n',
        '\nThe above exception was the direct cause of the following exception:\n\n',
        'Traceback (most recent call last):\n',
        '  File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 756, in create_commits\n    commit_info = retry_create_commit(\n',
        '  File "/src/services/worker/src/worker/utils.py", line 322, in decorator\n    raise RuntimeError(f"Give up after {attempt} attempts. The last one raised {type(last_err)}") from last_err\n',
        'RuntimeError: Give up after 6 attempts. The last one raised <class \'huggingface_hub.utils._errors.HfHubHTTPError\'>\n' ] },
  error_code: 'CreateCommitError',
  http_status: 500,
  job_runner_version: 3,
  progress: null,
  updated_at: 2023-06-20T19:14:32.580Z }
```

**Comment by severo** [comment]
Interestingly, we get no lock entry!

```
> use datasets_server_queue
< 'switched to db datasets_server_queue'
> db.locks.find({dataset: "severo/flores_101"})
< 
```

**Comment by severo** [comment]
As the lock entries are never deleted (they are only updated, to set `job_id` to `None`), it means that: no lock has ever been created for the dataset!

**Comment by severo** [comment]
https://github.com/huggingface/datasets-server/pull/1409 adds a unit test on `lock.git_branch`. It seems to work as expected.

**Comment by severo** [comment]
The query was wrong. We have a lock, as expected:

```
> db.locks.find({_id: '{"dataset": "severo/flores_101", "branch": "refs/convert/parquet"}'})
< { _id: '{"dataset": "severo/flores_101", "branch": "refs/convert/parquet"}',
  job_id: null,
  created_at: 2023-06-20T19:16:10.886Z,
  updated_at: 2023-06-20T19:16:44.859Z }
```

**Comment by severo** [comment]
The commits history (https://huggingface.co/datasets/severo/flores_101/commits/refs%2Fconvert%2Fparquet) contains 48 commits (the initial commit when we created the branch, then 47 commits to add parquet files, which is coherent with the 94 parquet files, as each config commits two parquet files, eg https://huggingface.co/datasets/severo/flores_101/commit/f40d7bb9e90fbb5f9fc986d325a245f124a67c64)

**Comment by severo** [comment]
Let's try https://github.com/huggingface/datasets-server/pull/1410

As it's difficult to test on multiple MongoDB replicas (we should do it at one point), I'll try to:
- merge to main
- deploy this on staging
- refresh the dataset severo/flores_101 from staging, which also have 3 replicas (beware, it writes to the Hub, as prod!)
- see if all the configs could be processed for the parquet creation, or if we still have an error for "half" of them

If it's fixed, deploy on prod. Else revert the commit, and keep trying.

**Comment by severo** [comment]
trying again with severo/flores_101 (deleting and recreating, to flush the parquet files and the cache in the DB)

**Comment by severo** [comment]
Same result (+1 failed config):
- 92 parquet files, from 46 configs
- 57 failed configs

**Comment by severo** [comment]
the underlying cause might be the same as #1323: concurrency issues when accessing to the MongoDB database

**Comment by severo** [comment]
By the way, I doubt it's due to replicas. By default, only the Primary is used for the reads and write, and by default w="majority", so... we should always be consistent.

I think the issue is more that we do several operations instead of one, and that we should do them in a transaction instead (not sure how we do this with mongoengine)

**Comment by severo** [comment]
Anyway, we could create a docker compose, with several concurrent workers and:
- 1 MongoDB replica
- 3 MongoDB replicas
and to try to replicate the issue

If we have it only with 1 MongoDB replica, it's not due to the replicas (or not only).

**Comment by severo** [comment]
I'll also send another PR where I reproduce the issue with commits, and do some other fixes.

**Comment by severo** [comment]
fixed by #1414. Confirmed by tests in #1415.
