### ISSUE TITLE
Descriptive stats: `duckdb.Error: Invalid Error: don't know what type`

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1830]
Happens e.g. for [xnli](https://huggingface.co/datasets/xnli) for the `all_languages` config for the `train` split
```
"Traceback (most recent call last):\n",
" File \"/src/services/worker/src/worker/job_manager.py\", line 160, in process\n job_result = self.job_runner.compute()\n",
" File \"/src/services/worker/src/worker/job_runners/split/descriptive_statistics.py\", line 404, in compute\n compute_descriptive_statistics_response(\n",
" File \"/src/services/worker/src/worker/job_runners/split/descriptive_statistics.py\", line 323, in compute_descriptive_statistics_response\n con.sql(\n",
"duckdb.Error: Invalid Error: don't know what type: \u000e\n"
```

cc @polinaeterna

**Comment by polinaeterna** [comment]
after refresh it's another error (file size doesn't match):

```
","  File "/src/services/worker/src/worker/job_manager.py", line 171, in process
    job_result = self.job_runner.compute()
","  File "/src/services/worker/src/worker/job_runners/split/descriptive_statistics.py", line 467, in compute
    compute_descriptive_statistics_response(
","  File "/src/services/worker/src/worker/job_runners/split/descriptive_statistics.py", line 352, in compute_descriptive_statistics_response
    hf_hub_download(
","  File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
","  File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1364, in hf_hub_download
    http_get(
","  File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 547, in http_get
    raise EnvironmentError(
","OSError: Consistency check failed: file should be of size 301736502 but has size 293192246 (0002.parquet).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
```

**Comment by severo** [comment]
https://datasets-server.huggingface.co/statistics?dataset=xnli&config=all_languages&split=train

> {"error":"Consistency check failed: file should be of size 301736502 but has size 293192246 (0002.parquet).\nWe are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.\nIf the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub."}

**Comment by AndreaFrancis** [comment]
After a refresh for https://datasets-server.huggingface.co/statistics?dataset=xnli&config=all_languages&split=train it is working fine 
![image](https://github.com/huggingface/datasets-server/assets/5564745/15736d88-e2d7-4971-9cd9-1adccfded4c4)
