### ISSUE TITLE
Retry on CreateCommitError?

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2159]
See https://huggingface.co/datasets/diffusers/pokemon-gpt4-captions/discussions/1#65662af89593e6086aff9bed

I imagine that two steps tried to send a commit at the same time.

The error was:

```json
{
    "error": "Commit 0/1 could not be created on the Hub (after 6 attempts).",
    "cause_exception": "HfHubHTTPError",
    "cause_message": "412 Client Error: Precondition Failed for url: https://huggingface.co/api/datasets/diffusers/pokemon-gpt4-captions/commit/refs%2Fconvert%2Fparquet (Request ID: Root=1-6565929c-547a1b5e442f9b9801ce82c4;f7b09dc5-dfe6-4889-bf81-50a6bebcd94b)\n\nA commit has happened since. Please refresh and try again.",
    "cause_traceback": [
        "Traceback (most recent call last):\n",
        ' File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status\n response.raise_for_status()\n',
        ' File "/src/services/worker/.venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status\n raise HTTPError(http_error_msg, response=self)\n',
        "requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: https://huggingface.co/api/datasets/diffusers/pokemon-gpt4-captions/commit/refs%2Fconvert%2Fparquet\n",
        "\nThe above exception was the direct cause of the following exception:\n\n",
        "Traceback (most recent call last):\n",
        ' File "/src/services/worker/src/worker/utils.py", line 205, in decorator\n return func(*args, **kwargs)\n',
        ' File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn\n return fn(*args, **kwargs)\n',
        ' File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 1150, in _inner\n return fn(self, *args, **kwargs)\n',
        ' File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 3534, in create_commit\n hf_raise_for_status(commit_resp, endpoint_name="commit")\n',
        ' File "/src/services/worker/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 330, in hf_raise_for_status\n raise HfHubHTTPError(str(e), response=response) from e\n',
        "huggingface_hub.utils._errors.HfHubHTTPError: 412 Client Error: Precondition Failed for url: https://huggingface.co/api/datasets/diffusers/pokemon-gpt4-captions/commit/refs%2Fconvert%2Fparquet (Request ID: Root=1-6565929c-547a1b5e442f9b9801ce82c4;f7b09dc5-dfe6-4889-bf81-50a6bebcd94b)\n\nA commit has happened since. Please refresh and try again.\n",
        "\nThe above exception was the direct cause of the following exception:\n\n",
        "Traceback (most recent call last):\n",
        ' File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 913, in create_commits\n commit_info = retry_create_commit(\n',
        ' File "/src/services/worker/src/worker/utils.py", line 210, in decorator\n raise RuntimeError(f"Give up after {attempt} attempts. The last one raised {type(last_err)}") from last_err\n',
        "RuntimeError: Give up after 6 attempts. The last one raised <class 'huggingface_hub.utils._errors.HfHubHTTPError'>\n",
    ],
}
```

**Comment by severo** [comment]
Done
