### ISSUE TITLE
The admin UI shows an error

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2228]
<img width="1050" alt="Capture d’écran 2024-01-02 à 18 55 20" src="https://github.com/huggingface/datasets-server/assets/1676121/2a24e7ca-1cda-42e0-b833-33688c2baf21">

**Comment by severo** [comment]
possibly due to the gradio upgrade? I didn't investigate

**Comment by severo** [comment]
The error:

```
Task exception was never retrieved
future: <Task finished name='2f4ftzk099c_7' coro=<Queue.process_events() done, defined at /home/user/.local/lib/python3.9/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 7, 'data': [...on_hash': '2f4ftzk099c'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/home/user/.local/lib/python3.9/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/home/user/.local/lib/python3.9/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/home/user/.local/lib/python3.9/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 7, 'data': [...on_hash': '2f4ftzk099c'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
```

**Comment by severo** [comment]
I temporarily reverted the gradio upgrade in the admin UI deployed in https://huggingface.co/spaces/datasets-maintainers/datasets-server-admin-ui. Related to #2225 and #2226. cc @albertvillanova .

Note that the "Error" badge still appears, but the app now works (I could create jobs to refresh cache entries).

**Comment by severo** [comment]
Setting P0 because we need the admin UI to be able to refresh datasets while doing support.

**Comment by severo** [comment]
> Note that the "Error" badge still appears, but the app now works (I could create jobs to refresh cache entries).

the "Error" badge does not appear anymore.

**Comment by severo** [comment]
I downgraded gradio in https://github.com/huggingface/datasets-server/pull/2305.

I opened a new issue that replaces this one: https://github.com/huggingface/datasets-server/issues/2306
