### ISSUE TITLE
staging-datasets-server-job-queue-metrics-collector-284267dkcp9 fails on staging

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2310]
```
Traceback (most recent call last):
  File "/src/jobs/cache_maintenance/src/cache_maintenance/main.py", line 11, in <module>
    from libcommon.storage_client import StorageClient
  File "/src/libs/libcommon/src/libcommon/storage_client.py", line 8, in <module>
    from libcommon.cloudfront import CloudFront
  File "/src/libs/libcommon/src/libcommon/cloudfront.py", line 8, in <module>
    from cryptography.hazmat.backends import default_backend
ModuleNotFoundError: No module named 'cryptography'
```

**Comment by severo** [comment]
I think it affects all the cache-maintenance based cron jobs

**Comment by severo** [comment]
fixed by https://github.com/huggingface/datasets-server/pull/2312
