### ISSUE TITLE
Support vectorial geospatial columns

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2416]
Requires https://github.com/huggingface/datasets/issues/6438, to support GeoParquet. We could support more formats.

Possibly requires geopandas as a dependency.

**Comment by severo** [comment]
at least, https://github.com/huggingface/datasets-server/issues/2428 will "Read GeoParquet files using parquet reader" https://github.com/huggingface/datasets/pull/6508

**Comment by weiji14** [comment]
Thanks @severo for opening this! As I understand, is an update needed on the server to pull in https://github.com/huggingface/datasets/pull/6508, so that GeoParquet datasets like https://huggingface.co/datasets/joshuasundance/govgis_nov2023-slim-spatial will show up on the Dataset Viewer?

**Comment by severo** [comment]
It does :)

<img width="912" alt="Capture d’écran 2024-02-12 à 23 06 03" src="https://github.com/huggingface/datasets-server/assets/1676121/703ef9cd-6e81-4c92-b670-a551834eb10d">

Note that we only have the first 100 rows on this dataset, because we ran into two other issues!


1. size of the row groups in the geoparquet files: 

```worker.job_runners.config.parquet_and_info.TooBigRowGroupsError: Parquet file has too big row groups. First row group has 950423110 which exceeds the limit of 300000000
```

2. issue with the features:

```
datasets.table.CastError: Couldn't cast
id: string
name: string
type: string
description: string
url: string
metadata_text: string
embeddings: list<element: double>
  child 0, element: double
geometry: binary
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' + 1178
geo: '{"primary_column": "geometry", "columns": {"geometry": {"encoding":' + 1306
to
{'id': Value(dtype='string', id=None), 'name': Value(dtype='string', id=None), 'type': Value(dtype='string', id=None), 'description': Value(dtype='string', id=None), 'url': Value(dtype='string', id=None), 'metadata_text': Value(dtype='string', id=None), 'geometry': Value(dtype='binary', id=None)}
because column names don't match
```

**Comment by weiji14** [comment]
Awesome, this is a big step forward!

> size of the row groups in the geoparquet files:

To be honest, 950423110 does seem like a bit much for a single row group, but a row group shouldn't be too small either. DuckDB has some nice about this here - https://duckdb.org/docs/guides/performance/file_formats#the-effect-of-row-group-sizes

> issue with the features:

Hmm, which field is the `CastError` on? Is it something in the schema metadata? The log seems truncated or something, so I can't quite tell.

**Comment by severo** [comment]
the full traceback

```
Traceback (most recent call last):
  File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 1169, in compute_config_parquet_and_info_response
      fill_builder_info(builder, hf_endpoint=hf_endpoint, hf_token=hf_token, validate=validate)
  File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 619, in fill_builder_info
      parquet_files_and_sizes: list[tuple[pq.ParquetFile, int]] = thread_map(
  File "/src/services/worker/.venv/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
      return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/src/services/worker/.venv/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
      return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/src/services/worker/.venv/lib/python3.9/site-packages/tqdm/std.py", line 1166, in __iter__
      for obj in iterable:
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
      yield fs.pop().result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
      return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
      raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
      result = self.fn(*self.args, **self.kwargs)
  File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 556, in retry_and_validate_get_parquet_file_and_size
      validate(pf)
  File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 588, in validate
      raise TooBigRowGroupsError(
  worker.job_runners.config.parquet_and_info.TooBigRowGroupsError: Parquet file has too big row groups. First row group has 950423110 which exceeds the limit of 300000000


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/builder.py", line 1973, in _prepare_split_single
      for _, table in generator:
  File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 712, in wrapped
      for item in generator(*args, **kwargs):
  File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/packaged_modules/parquet/parquet.py", line 94, in _generate_tables
      yield f"{file_idx}_{batch_idx}", self._cast_table(pa_table)
  File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/packaged_modules/parquet/parquet.py", line 74, in _cast_table
      pa_table = table_cast(pa_table, self.info.features.arrow_schema)
  File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/table.py", line 2240, in table_cast
      return cast_table_to_schema(table, schema)
  File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/table.py", line 2194, in cast_table_to_schema
      raise CastError(
  datasets.table.CastError: Couldn't cast
id: string
name: string
type: string
description: string
url: string
metadata_text: string
embeddings: list<element: double>
  child 0, element: double
geometry: binary
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' + 1178
geo: '{"primary_column": "geometry", "columns": {"geometry": {"encoding":' + 1306
to
{'id': Value(dtype='string', id=None), 'name': Value(dtype='string', id=None), 'type': Value(dtype='string', id=None), 'description': Value(dtype='string', id=None), 'url': Value(dtype='string', id=None), 'metadata_text': Value(dtype='string', id=None), 'geometry': Value(dtype='binary', id=None)}
because column names don't match


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/src/services/worker/src/worker/job_manager.py", line 158, in process
      job_result = self.job_runner.compute()
  File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 1288, in compute
      compute_config_parquet_and_info_response(
    File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 1178, in compute_config_parquet_and_info_response
      parquet_operations, partial = stream_convert_to_parquet(
    File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 802, in stream_convert_to_parquet
      builder._prepare_split(
    File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/builder.py", line 1860, in _prepare_split
      for job_id, done, content in self._prepare_split_single(
    File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/builder.py", line 2016, in _prepare_split_single
      raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset
```

**Comment by severo** [comment]
geopandas has reached 1.0.0

https://github.com/geopandas/geopandas/releases/tag/v1.0.0

**Comment by cholmes** [comment]
> size of the row groups in the geoparquet files:
> `worker.job_runners.config.parquet_and_info.TooBigRowGroupsError: Parquet file has too big row groups. First row group has 950423110 which exceeds the limit of 300000000`

What dataset is this from? That's not a geoparquet thing - I'm working on a guide for GeoParquet row group size and 950m is way, way bigger than we'd recommend.

Also I think there's a potentially smaller improvement to make, that I think shouldn't require GeoPandas (though it's an option). The geometry column is a widely adopted standard called 'Well Known Binary', that is the binary equivalent of 'Well Known Text'. See https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry for explanation. There's lots of WKB parsers, and if the dataset viewer just displayed the well-known text representations of the WKB (like `POINT (30 10)`) then that'd be a nice step forward. You could even do it in javascript on the client side.

An ideal version would read the parquet geo metadata and get the geometry columns that way (and you shouldn't need full geopandas to do that, just parse the parquet metadata). A naive version could just look for 'geometry' and 'geom' column names and likely get it right 80%+ of the time.

**Comment by cholmes** [comment]
Oh, I read up a bit more, and looks like the front-end code isn't open source. So I can't try to make a PR :) 

It shouldn't be much work to have the front-end code just make a WKT representation, and this is what most of the geo database software does (PostGIS, BigQuery, etc)

**Comment by cfahlgren1** [comment]
Hey @cholmes, good news is in the meantime you can use the SQL Console along with DuckDB [geospatial functions](https://duckdb.org/docs/extensions/spatial/functions#st_asgeojson) to do this for datasets that have that column. Here's an [example](https://huggingface.co/datasets/weiji14/clay_vector_embeddings?sql_console=true&sql=select+ST_AsText%28geometry%29%2C+ST_AsGeoJSON%28geometry%29%0Afrom+train+limit+100&sql_row=0) for the [weiji14/clay_vector_embeddings dataset](https://huggingface.co/datasets/weiji14/clay_vector_embeddings)

![image](https://github.com/user-attachments/assets/57a3f397-df6f-4d43-badd-0959d5a3e80f)
