### ISSUE TITLE
statistics fail on 2A2I/Arabic-OpenHermes-2.5

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2529]
https://huggingface.co/datasets/2A2I/Arabic-OpenHermes-2.5

the error:

```json
{
    "error": "unsupported operand type(s) for *: 'NoneType' and 'float'",
    "cause_exception": "TypeError",
    "cause_message": "unsupported operand type(s) for *: 'NoneType' and 'float'",
    "cause_traceback": [
        "Traceback (most recent call last):\n",
        ' File "/src/services/worker/src/worker/job_manager.py", line 125, in process\n job_result = self.job_runner.compute()\n',
        ' File "/src/services/worker/src/worker/job_runners/split/descriptive_statistics.py", line 651, in compute\n compute_descriptive_statistics_response(\n',
        ' File "/src/services/worker/src/worker/job_runners/split/descriptive_statistics.py", line 608, in compute_descriptive_statistics_response\n stats = compute_descriptive_statistics_for_features(\n',
        ' File "/src/services/worker/src/worker/job_runners/split/descriptive_statistics.py", line 421, in compute_descriptive_statistics_for_features\n numerical_column_stats = compute_numerical_statistics(\n',
        ' File "/src/services/worker/src/worker/job_runners/split/descriptive_statistics.py", line 236, in compute_numerical_statistics\n minimum, maximum, mean, median, std = np.round([minimum, maximum, mean, median, std], DECIMALS).tolist()\n',
        ' File "<__array_function__ internals>", line 180, in round_\n',
        ' File "/src/services/worker/.venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3773, in round_\n return around(a, decimals=decimals, out=out)\n',
        ' File "<__array_function__ internals>", line 180, in around\n',
        " File \"/src/services/worker/.venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py\", line 3348, in around\n return _wrapfunc(a, 'round', decimals=decimals, out=out)\n",
        ' File "/src/services/worker/.venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc\n return _wrapit(obj, method, *args, **kwds)\n',
        ' File "/src/services/worker/.venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit\n result = getattr(asarray(obj), method)(*args, **kwds)\n',
        "TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'\n",
    ],
}
```

**Comment by severo** [comment]
cc @polinaeterna maybe

**Comment by polinaeterna** [comment]
will take a look rrn

**Comment by polinaeterna** [comment]
seems that the whole column is `null`, so min, max, etc. are `None` values and this error happens when trying to round None values, I can include fix in https://github.com/huggingface/datasets-server/pull/2453

**Comment by AndreaFrancis** [comment]
Looks duplicated of https://github.com/huggingface/datasets-server/issues/1843
