### ISSUE TITLE
e2e is broken due to KenLM install

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#2636]
We get:

```
Note: This error originates from the build backend, and is likely not a problem with poetry but with kenlm (0.2.0 https://github.com/kpu/kenlm/archive/master.zip) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "kenlm @ https://github.com/kpu/kenlm/archive/master.zip"'.
```

Running this command gives:

```
$ poetry run pip wheel --no-cache-dir --use-pep517 "kenlm @ https://github.com/kpu/kenlm/archive/master.zip"
Collecting kenlm@ https://github.com/kpu/kenlm/archive/master.zip
  Downloading https://github.com/kpu/kenlm/archive/master.zip
     \ 553.6 kB 4.7 MB/s 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: kenlm
  Building wheel for kenlm (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for kenlm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      Will build with KenLM max_order set to 6
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "/tmp/pip-build-env-irk6jevh/overlay/bin/cmake", line 5, in <module>
          from cmake import cmake
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/cmake/__init__.py", line 6, in <module>
          from importlib_metadata import distribution
      ModuleNotFoundError: No module named 'importlib_metadata'
      Traceback (most recent call last):
        File "/home/slesage/hf/datasets-server/services/worker/.venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/slesage/hf/datasets-server/services/worker/.venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/slesage/hf/datasets-server/services/worker/.venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 124, in <module>
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-irk6jevh/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 64, in run
        File "/home/slesage/.pyenv/versions/3.9.18/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/slesage/.pyenv/versions/3.9.18/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kenlm
Failed to build kenlm
ERROR: Failed to build one or more wheels
```

**Comment by severo** [comment]
I'm not sure we still need KenLM?

It would be interesting to:
- list the authorized script-based datasets
- analyze their scripts to find the import statements
- find if we can remove some of the installed libraries, in particular KenLM

**Comment by severo** [comment]
I ran https://huggingface.co/spaces/severo/find_script_based_datasets_dependencies on these 714 datasets.

The only dependencies we need in services/worker are:

```
bigbench
conllu
datasets
faiss
h5py
huggingface_hub
lxml
numpy
openpyxl
pandas
py7zr
pyarrow
scipy
sentencepiece
tqdm
zstandard
```

Note that we don't support `bigbench`. I'll open a PR to remove all the dependencies we don't need.

**Comment by severo** [comment]
see https://github.com/huggingface/datasets-server/pull/2637
