### ISSUE TITLE
Dataset Viewer issue for severo/empty_public

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#584]
### Link

https://huggingface.co/datasets/severo/empty_public

### Description

The dataset viewer is not working for dataset severo/empty_public.

Error details:

```
Error code:   EmptyDatasetError
Exception:    EmptyDatasetError
Message:      The dataset repository at 'severo/empty_public' doesn't contain any data files
Traceback:    Traceback (most recent call last):
                File "/src/services/worker/src/worker/responses/splits.py", line 79, in get_splits_response
                  split_full_names = get_dataset_split_full_names(dataset, hf_token)
                File "/src/services/worker/src/worker/responses/splits.py", line 41, in get_dataset_split_full_names
                  for config in get_dataset_config_names(dataset, use_auth_token=hf_token)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/inspect.py", line 308, in get_dataset_config_names
                  dataset_module = dataset_module_factory(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1171, in dataset_module_factory
                  raise e1 from None
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1156, in dataset_module_factory
                  return HubDatasetModuleFactoryWithoutScript(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 760, in get_module
                  else get_data_patterns_in_dataset_repository(hfh_dataset_info, self.data_dir)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/data_files.py", line 676, in get_data_patterns_in_dataset_repository
                  raise EmptyDatasetError(
              datasets.data_files.EmptyDatasetError: The dataset repository at 'severo/empty_public' doesn't contain any data files
```

cc @albertvillanova @lhoestq @severo.

**Comment by severo** [comment]
it was a test
