### ISSUE TITLE
Dataset Viewer issue for GEM/wiki_lingua

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#585]
### Link

https://huggingface.co/datasets/GEM/wiki_lingua

### Description

The dataset viewer is not working for dataset GEM/wiki_lingua.

Error details:

```
Error code:   StreamingRowsError
Exception:    NotImplementedError
Message:      Extraction protocol for TAR archives like 'https://huggingface.co/datasets/GEM/wiki_lingua/resolve/main/wikilingua_cleaned.tar.gz' is not implemented in streaming mode. Please use `dl_manager.iter_archive` instead.
Traceback:    Traceback (most recent call last):
                File "/src/services/worker/src/worker/responses/first_rows.py", line 337, in get_first_rows_response
                  rows = get_rows(dataset, config, split, streaming=True, rows_max_number=rows_max_number, hf_token=hf_token)
                File "/src/services/worker/src/worker/utils.py", line 123, in decorator
                  return func(*args, **kwargs)
                File "/src/services/worker/src/worker/responses/first_rows.py", line 65, in get_rows
                  ds = load_dataset(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/load.py", line 1739, in load_dataset
                  return builder_instance.as_streaming_dataset(split=split)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/builder.py", line 1025, in as_streaming_dataset
                  splits_generators = {sg.name: sg for sg in self._split_generators(dl_manager)}
                File "/tmp/modules-cache/datasets_modules/datasets/GEM--wiki_lingua/84e1fa083237de0bf0016a1934d8b659ecafd567f398012ca5d702b7acc97450/wiki_lingua.py", line 184, in _split_generators
                  dl_dir = dl_manager.download_and_extract(_URL)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/download/streaming_download_manager.py", line 944, in download_and_extract
                  return self.extract(self.download(url_or_urls))
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/download/streaming_download_manager.py", line 907, in extract
                  urlpaths = map_nested(self._extract, path_or_paths, map_tuple=True)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/utils/py_utils.py", line 385, in map_nested
                  return function(data_struct)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/download/streaming_download_manager.py", line 912, in _extract
                  protocol = _get_extraction_protocol(urlpath, use_auth_token=self.download_config.use_auth_token)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/download/streaming_download_manager.py", line 390, in _get_extraction_protocol
                  raise NotImplementedError(
              NotImplementedError: Extraction protocol for TAR archives like 'https://huggingface.co/datasets/GEM/wiki_lingua/resolve/main/wikilingua_cleaned.tar.gz' is not implemented in streaming mode. Please use `dl_manager.iter_archive` instead.
```

**Comment by severo** [comment]
test
