### ISSUE TITLE
Github Dataset not Downloaded

### ISSUE THREAD

**Issue by MiWeiss** [huggingface/datasets-server#942]
### Link

https://huggingface.co/datasets/mweiss/fashion_mnist_corrupted

### Description

```
Error code:   StreamingRowsError
Exception:    FileNotFoundError
Message:      [Errno 2] No such file or directory: 'https://github.com/testingautomated-usi/fashion-mnist-c/raw/v1.0.0/generated/npy/fmnist-c-train.npy'
Traceback:    Traceback (most recent call last):
                File "/src/services/worker/src/worker/job_runners/first_rows.py", line 570, in compute_first_rows_response
                  rows = get_rows(
                File "/src/services/worker/src/worker/job_runners/first_rows.py", line 161, in decorator
                  return func(*args, **kwargs)
                File "/src/services/worker/src/worker/job_runners/first_rows.py", line 217, in get_rows
                  rows_plus_one = list(itertools.islice(ds, rows_max_number + 1))
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 937, in __iter__
                  for key, example in ex_iterable:
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 113, in __iter__
                  yield from self.generate_examples_fn(**self.kwargs)
                File "/tmp/modules-cache/datasets_modules/datasets/mweiss--fashion_mnist_corrupted/eb400b17b13bc9eff3632e537102d6486ced9893ea148a5b41c8eca38b36f7ce/fashion_mnist_corrupted.py", line 120, in _generate_examples
                  images = np.load(filepath[0])
                File "/src/services/worker/.venv/lib/python3.9/site-packages/numpy/lib/npyio.py", line 407, in load
                  fid = stack.enter_context(open(os_fspath(file), "rb"))
              FileNotFoundError: [Errno 2] No such file or directory: 'https://github.com/testingautomated-usi/fashion-mnist-c/raw/v1.0.0/generated/npy/fmnist-c-train.npy'
```

I am not sure about the root cause of this error. After all, the url [https://github.com/testingautomated-usi/fashion-mnist-c/raw/v1.0.0/generated/npy/fmnist-c-train.npy](https://github.com/testingautomated-usi/fashion-mnist-c/raw/v1.0.0/generated/npy/fmnist-c-train.npy) is correct.

Does huggingface-server somehow block github urls? Or are you aware that huggingface requests get blocked by github?

**Comment by severo** [comment]
Have you tried using https://raw.githubusercontent.com/testingautomated-usi/fashion-mnist-c/v1.0.0/generated/npy/fmnist-c-train.npy instead?

**Comment by MiWeiss** [comment]
Thanks for the proposition. I have updated the script - so far, the preview has not been re-created (there's still the old error message). I will come back to this issue once anything has changed...

**Comment by severo** [comment]
Could you have a look at this dataset too, @albertvillanova?

**Comment by MiWeiss** [comment]
> Thanks for the proposition. I have updated the script - so far, the preview has not been re-created (there's still the old error message). I will come back to this issue once anything has changed...

The error has now changed, but there's still an error. I have not changed anything other than the DL path...

**Comment by albertvillanova** [comment]
Sure, I'm having a look at it...

**Comment by albertvillanova** [comment]
I'm transferring this issue to the Hub: https://huggingface.co/datasets/mweiss/fashion_mnist_corrupted/discussions/2

Let's continue the discussion there.
