### ISSUE TITLE
Dataset Viewer issue for allenai/objaverse

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#979]
### Link

https://huggingface.co/datasets/allenai/objaverse

### Description

This error should be "tagged" as a server error, not a "dataset" error, and should propose to create an issue, not to open a discussion.
Also, note that we would want to retry automatically later in that case.

```
Error code:   FeaturesError
Exception:    HfHubHTTPError
Message:      504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/allenai/objaverse
Traceback:    Traceback (most recent call last):
                File "/src/workers/datasets_based/src/datasets_based/workers/first_rows.py", line 465, in compute_first_rows_response
                  iterable_dataset = load_dataset(
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/load.py", line 1734, in load_dataset
                  builder_instance = load_dataset_builder(
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/load.py", line 1492, in load_dataset_builder
                  dataset_module = dataset_module_factory(
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/load.py", line 1216, in dataset_module_factory
                  raise e1 from None
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/load.py", line 1185, in dataset_module_factory
                  raise e
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/load.py", line 1157, in dataset_module_factory
                  dataset_info = hf_api_dataset_info(
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/datasets/utils/_hf_hub_fixes.py", line 152, in dataset_info
                  return hf_api.dataset_info(repo_id, revision=revision, timeout=timeout, use_auth_token=use_auth_token)
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
                  return fn(*args, **kwargs)
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 1299, in dataset_info
                  hf_raise_for_status(r)
                File "/src/workers/datasets_based/.venv/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 280, in hf_raise_for_status
                  raise HfHubHTTPError(str(e), response=response) from e
              huggingface_hub.utils._errors.HfHubHTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/datasets/allenai/objaverse
```

<img width="1021" alt="Capture d’écran 2023-03-23 à 12 50 13" src="https://user-images.githubusercontent.com/1676121/227195409-597b3967-8488-46f0-bbd2-21b0f6e28a7d.png">

**Comment by severo** [comment]
Oh, not sure, see https://huggingface.co/datasets/allenai/objaverse/discussions/6

**Comment by severo** [comment]
Mentioned here: https://youtu.be/0o1P6h36_V4?t=253
